apiVersion: v1
kind: Service
metadata:
  name: {{ include "bosun.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector: { app.kubernetes.io/name: bosun }
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
