apiVersion: v1
kind: Service
metadata:
  name: {{ include "bosun.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "bosun.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
